name: Deploy

on: 
  workflow_dispatch:
  release:
    types: [published]

env: 
  AZURE_WEBAPP_NAME: traffilearn-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: "8.x"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ./src/TraffiLearn.sln

      - name: Build
        run: dotnet build ./src/TraffiLearn.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/TraffiLearn.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Configure Azure App Service Settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group <your-resource-group> --settings \
              DbSettings__ConnectionString=${{ secrets.DB_CONNECTION_STRING }} \
              JwtSettings__SecretKey=${{ secrets.JWT_SECRET_KEY }} \
              JwtSettings__Issuer=${{ secrets.JWT_ISSUER }} \
              JwtSettings__Audience=${{ secrets.JWT_AUDIENCE }} \
              GroqApiSettings__Model=${{ secrets.GROQ_API_MODEL }} \
              GroqApiSettings__CreateChatCompletionUri=${{ secrets.GROQ_API_CREATE_CHAT_COMPLETION_URI }} \
              GroqApiSettings__BaseUri=${{ secrets.GROQ_API_BASE_URI }} \
              GroqApiSettings__ApiKey=${{ secrets.GROQ_API_KEY }} \
              SuperUserSettings__Username=${{ secrets.SUPER_USER_USERNAME }} \
              SuperUserSettings__Email=${{ secrets.SUPER_USER_EMAIL }} \
              SuperUserSettings__Password=${{ secrets.SUPER_USER_PASSWORD }}
      
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
