name: Build

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: "8.x"

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up Environment Variables
        run: |
          echo "DbSettings__ConnectionString=${{ secrets.DB_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "JwtSettings__SecretKey=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "JwtSettings__Issuer=${{ secrets.JWT_ISSUER }}" >> $GITHUB_ENV
          echo "JwtSettings__Audience=${{ secrets.JWT_AUDIENCE }}" >> $GITHUB_ENV

      - name: Clean Solution
        run: dotnet clean ./src/TraffiLearn.sln

      - name: Restore
        run: dotnet restore ./src/TraffiLearn.sln

      - name: Build
        run: dotnet build ./src/TraffiLearn.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/TraffiLearn.sln --configuration Release --no-restore --no-build --logger "trx;LogFileName=tests_results.trx" --results-directory ./TestResults

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Notify on Failure
        if: failure()
        run: echo "Build failed."

      - name: Notify on Success
        if: success()
        run: echo "Build and tests succeeded."
